/*
 Generated by:

 var outputs = "var imageNames = [ \n";

 $('.rgAltRow img, .rgRow img').each(function(){
 var imgPath = $(this).attr('src');
 var imgName = imgPath.match(/\/(\w+)\.png/)[1];
 console.log(imgName);
 outputs += "'" + imgName + "', \n";
 });

 outputs += '];';

 console.log(outputs);

 */

var imageNames = [
  'TheLostVikings',
  'Brightwing',
  'Rehgar',
  'Uther',
  'Sylvanas',
  'Azmodan',
  'Thrall',
  'ETC',
  'Gazlowe',
  'Valla',
  'Jaina',
  'Tyrael',
  'Zagara',
  'Illidan',
  'SgtHammer',
  'Nazeebo',
  'Diablo',
  'Tyrande',
  'LiLi',
  'Zeratul',
  'Nova',
  'Anubarak',
  'Stitches',
  'Tassadar',
  'Malfurion',
  'Chen',
  'Kerrigan',
  'Falstad',
  'Tychus',
  'AutoSelect',
  'Muradin',
  'Arthas',
  'Murky',
  'Abathur',
  'Raynor',
  'Sonya',
  //'BlackheartsBay',
  //'CursedHollow',
  //'DragonShire',
  //'GardenofTerror',
  //'HauntedMines',
  //'SkyTemple',
  //'TomboftheSpiderQueen',
];

var heroImages = {
  'The Lost Vikings': 'TheLostVikings',
  'Brightwing': 'Brightwing',
  'Rehgar': 'Rehgar',
  'Uther': 'Uther',
  'Sylvanas': 'Sylvanas',
  'Azmodan': 'Azmodan',
  'Thrall': 'Thrall',
  'E.T.C.': 'ETC',
  'Gazlowe': 'Gazlowe',
  'Valla': 'Valla',
  'Jaina': 'Jaina',
  'Tyrael': 'Tyrael',
  'Zagara': 'Zagara',
  'Illidan': 'Illidan',
  'Sgt. Hammer': 'SgtHammer',
  'Nazeebo': 'Nazeebo',
  'Diablo': 'Diablo',
  'Tyrande': 'Tyrande',
  'Li Li': 'LiLi',
  'Zeratul': 'Zeratul',
  'Nova': 'Nova',
  "Anub'arak": 'Anubarak',
  'Stitches': 'Stitches',
  'Tassadar': 'Tassadar',
  'Malfurion': 'Malfurion',
  'Chen': 'Chen',
  'Kerrigan': 'Kerrigan',
  'Falstad': 'Falstad',
  'Tychus': 'Tychus',
  'AutoSelect': 'AutoSelect',
  'Muradin': 'Muradin',
  'Arthas': 'Arthas',
  'Murky': 'Murky',
  'Abathur': 'Abathur',
  'Raynor': 'Raynor',
  'Sonya': 'Sonya',
};


var getImageName = function (name) {
  if (imageNames.indexOf(name) > 0) {
    return name;
  } else {
    return 'AutoSelect';
  }
};

var getHeroImage = function (heroName) {
  var imageName = heroImages[heroName];

  if (typeof imageName !== 'undefined') {
    return imageName;
  } else {
    return 'AutoSelect';
  }
};

exports.getHeroImage = getHeroImage;
exports.getImageName = getImageName;